#!/usr/bin/bash

# Variables
debug=2
rebos_path="$HOME/.config/rebos"
rebos_system_files_path="$rebos_path/system_files"
rebos_dotfiles_path="$rebos_system_files_path/dotfiles"
rebos_gitconfig_path="$rebos_dotfiles_path/gitconfig.conf"
rebos_sysconfigs_path="$rebos_system_files_path/sys-configs"

# Add git integration into FZF
echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Configuring fzf"
[ $debug -ge 2 ] && echo -e "\033[0;90m[\033[1;94mDebug\033[0;90m] :\033[0m Checking to see if plugin is downloaded"
if [ -d "$HOME/fzf-git.sh" ]; then
  [ $debug -ge 2 ] && echo -e "\033[0;90m[\033[1;94mDebug\033[0;90m] :\033[0m Plugin is already downloaded" 
  [ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;94mDebug\033[0;90m] :\033[0m Pulling latest git commit"
  pushd "$HOME/fzf-git.sh"
  git pull
  popd
else
  [ $debug -ge 2 ] && echo -e "\033[0;90m[\033[1;94mDebug\033[0;90m] :\033[0m Plugin is not downloaded"
  [ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;94mDebug\033[0;90m] :\033[0m Downloading plugin"
  if [ $debug -ge 1 ]; then  
    git clone https://github.com/junegunn/fzf-git.sh.git $HOME/fzf-git.sh || exit 1
  else 
    git clone https://github.com/junegunn/fzf-git.sh.git $HOME/fzf-git.sh > /dev/null || exit 1 # Disable stdout
  fi
fi

# Configure bat
echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Configuring bat"
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Creating $(bat --config-dir)/themes if it does not already exist"
[ -d "$(bat --config-dir)/themes" ] || mkdir -p "$(bat --config-dir)/themes" || exit 1
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Downloading bat theme"
pushd "$(bat --config-dir)/themes"
if [ $debug -ge 2 ]; then
  curl -O "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/sublime/tokyonight_night.tmTheme"
else
  curl -O "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/sublime/tokyonight_night.tmTheme" > /dev/null
fi
popd
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Building bat cache"
bat cache --build || exit 1

# Configure nerd-fonts
echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Configuring Nerd Fonts"
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Cloning git repository"
if [ $debug -ge 1 ]; then
  git clone https://github.com/ryanoasis/nerd-fonts.git /tmp/nerd-fonts || exit 1
else
  git clone https://github.com/ryanoasis/nerd-fonts.git /tmp/nerd-fonts > /dev/null || exit 1
fi
pushd /tmp/nerd-fonts
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Running nerd-fonts install script"
[ $debug -ge 2 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Installing UbuntuSans"
./install.sh UbuntuSans
