#!/usr/bin/bash

# Variables
debug=1

# Configure GURU
echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Configuring additional repositories"
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;94mDebug\033[0;90m] :\033[0m Enabling solopasha/hyprland repository"
sudo dnf copr enable solopasha/hyprland

# Configure flatpak
echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Configuring Flatpak"
if [ $debug -ge 1 ]; then
  echo -e "\033[0;90m[\033[1;94mDebug\033[0;90m] :\033[0m Enable Flathub for Flatpaks"
  flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo || exit 1
else 
  flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo > /dev/null || exit 1
fi
