# Flatpak

add = "yes "" | flatpak install --user #:?"
remove = "flatpak uninstall --user #:?"
upgrade = "flatpak upgrade --user"

plural_name = "flatpak"

hook_name = "flatpak"

[config]
many_args = false
