# Flatpak

add = "flatpak install --user --assumeyes #:?"
remove = "flatpak uninstall --user --assumeyes #:?"
upgrade = "flatpak upgrade --user --assumeyes" 

plural_name = "flatpak"

hook_name = "flatpak"

[config]
many_args = true
