#!/usr/bin/bash

# Variables
debug=2
rebos_path="$HOME/.config/rebos"
rebos_system_files_path="$rebos_path/system_files"
rebos_dotfiles_path="$rebos_system_files_path/dotfiles"
rebos_gitconfig_path="$rebos_dotfiles_path/gitconfig.conf"
rebos_sysconfigs_path="$rebos_system_files_path/sys-configs"

# Add user to seat and video groups
echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Adding $USER to necessary groups"
