#!/bin/bash

# Define variables
debug=2
rebos_path="$HOME/.config/rebos"
rebos_system_files="$rebos_path/system_files"
rebos_sysconfigs_path="$rebos_path/system_files/sys-configs"
rebos_zshrc="$rebos_system_files/zshrc.sh"

# Manually set GPG settings if GPG is not on
echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Setting GPG settings manually (in case this is a first install)"
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Checking to see if gpg-agent is running" #TODO: fix me
gpgconf --kill gpg-agent # TEMP
unset SSH_AGENT_PID
if [ ${gnupg_SSH_AUTH_SOCK_bye-:0} -ne $$ ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs gpg-agent)"
fi
gpgconf -launch gpg-agent
gpg-connect-agent updatestartuptty /bye > /dev/null
export GPG_TTY="$(tty)"

# Restore stowed configs (if ~/dotfiles exists)
echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Restoring configurations"
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Checking to see if $HOME/dotfiles exists"
if [ -d "$HOME/dotfiles" ]; then
  [ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m $HOME/dotfiles exists"
else
  [ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m $HOME/dotfiles does not exist. Attempting to pull latest git commit"
  if [ $debug -ge 2 ]; then
    git clone https://github.com/arltk/dotfiles --recurse $HOME/dotfiles
  else
    git clone https://github.com/arltk/dotfiles --recurse $HOME/dotfiles > /dev/null
  fi
fi
[ $debug -ge 2 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Checking to see if app-admin/stow is installed"
[ ! $(command -v stow) ] && echo -e "\033[0;90m[\033[1;91mError\033[0;90m] :\033[0m Stow is not installed" && exit 1
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Stowing all dotfiles"
pushd "$HOME/dotfiles/"
stow --adopt * || exit 1
if [ $debug -ge 2 ]; then
  git restore . || exit 1
else
  git restore . > /dev/null || exit 1
fi
popd

#TODO:
# Refactor to use custom $groups variable and account for multiple groups
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;94mDebug\033[0;90m] :\033[0m Adding $USER to groups"
sudo usermod -aG seat,video $USER

# Add git integration into FZF
echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Configuring fzf"
if [ $debug -ge 1 ]; then  
  echo -e "\033[0;90m[\033[1;94mDebug\033[0;90m] :\033[0m Downloading git info"
  rm -rf "$HOME/fzf-git.sh/"
  git clone https://github.com/junegunn/fzf-git.sh.git $HOME/fzf-git.sh || exit 1
else 
  git clone https://github.com/junegunn/fzf-git.sh.git $HOME/fzf-git.sh > /dev/null || exit 1 # Disable stdout
fi

# Configure bat
echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Configuring bat"
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Creating $(bat --config-dir)/themes if it does not already exist"
[ -d "$(bat --config-dir)/themes" ] || mkdir -p "$(bat --config-dir)/themes" || exit 1
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Downloading bat theme"
pushd "$(bat --config-dir)/themes"
if [ $debug -ge 2 ]; then
  curl -O "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/sublime/tokyonight_night.tmTheme"
else
  curl -O "https://raw.githubusercontent.com/folke/tokyonight.nvim/main/extras/sublime/tokyonight_night.tmTheme" > /dev/null
fi
popd
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Building bat cache"
bat cache --build || exit 1

# Copy SDDM configs
echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Copying SDDM configs"
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Copying $rebos_sysconfigs_path/sddm.conf -> /etc/sddm.conf.d/01gentoo.conf"
if [ $debug -ge 2 ]; then
  sudo cp -v "$rebos_sysconfigs_path/sddm.conf" "/etc/sddm.conf.d/01gentoo.conf" || exit 1
else 
  sudo cp "$rebos_sysconfigs_path/sddm.conf" "/etc/sddm.conf.d/01gentoo.conf" || exit 1
fi

# Copy RC configs
echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Copying RC configs"
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Copying $rebos_sysconfigs_path/rc.conf -> /etc/rc.conf"
if [ $debug -ge 2 ]; then
  sudo cp -v "$rebos_sysconfigs_path/rc.conf" "/etc/rc.conf" || exit 1
else
  sudo cp "$rebos_sysconfigs_path/rc.conf" "/etc/rc.conf" || exit 1
fi

# Copy update command
echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Copying update command"
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Copying $rebos_system_files/scripts/update-system.sh -> /usr/local/bin/update"
if [ $debug -ge 2 ]; then
  sudo cp -v "$rebos_system_files/scripts/update-system.sh" "/usr/local/bin/update" || exit 1
else
  sudo cp "$rebos_system_files/scripts/update-system.sh" "/usr/local/bin/update" || exit 1
fi
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Changing permissions on /usr/local/bin/update"
sudo chmod +x "/usr/local/bin/update"

# Install proton-ge
echo -e "\033[0;90m[\033[1;92mInfo\033[0;90m] :\033[0m Installing proton-ge"
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;94mDebug\033[0;90m] :\033[0m Create temporary working directory for proton-ge"
[ $debug -ge 2 ] && rm -rfv /tmp/proton-ge-custom || rm -rfv /tmp/proton-ge-custom
mkdir /tmp/proton-ge-custom
pushd /tmp/proton-ge-custom
tarball_url=$(curl -s https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases/latest | grep browser_download_url | cut -d\" -f4 | grep .tar.gz)
tarball_name=$(basename $tarball_url)
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;94mDebug\033[0;90m] :\033[0m Downloading tarball: $tarball_name"
[ $debug -ge 2 ] && curl -# -L $tarball_url -o $tarball_name || curl -# -L $tarball_url -o $tarball_name --no-progress-meter
checksum_url=$(curl -s https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases/latest | grep browser_download_url | cut -d\" -f4 | grep .sha512sum)
checksum_name=$(basename $checksum_url)
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;94mDebug\033[0;90m] :\033[0m Downloading checksum: $checksum_name"
[ $debug -ge 2 ] && curl -# -L $checksum_url -o $checksum_name || curl -# -L $checksum_url -o $checksum_name --no-progress-meter
[ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;94mDebug\033[0;90m] :\033[0m Verifying tarball $tarball_name with checksum $checksum_name"
if sha512sum -c $checksum_name; then
  [ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;94mDebug\033[0;90m] :\033[0m Checksum is correct"
  [ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;94mDebug\033[0;90m] :\033[0m Extracting tarball"
  mkdir -p ~/.steam/steam/compatibilitytools.d
  [ $debug -ge 2 ] && tar -xvf $tarball_name -C ~/.steam/steam/compatibilitytools.d/ || tar -xf $tarball_name -C ~/.steam/steam/compatibilitytools.d/
else
  [ $debug -ge 1 ] && echo -e "\033[0;90m[\033[1;91mError\033[0;90m] :\033[0m Checksum does not match"
fi
popd
