[managers.system]
items = [
  "firefox", # Web browser, requires configs or sync
  "remmina", # RDP & remote-access client
]

[managers.flatpak]
items = [
  # Standard packages
  "com.dec05eba.gpu_screen_recorder", # NVIDIA Shadowplay clone
  "com.discordapp.Discord", # Discord client
  "com.protonvpn.www", # ProtonVPN client
  #"me.proton.Mail", # ProtonMail client, might want to forego this in favor of using the web browser

  # Direct links
  "https://sober.vinegarhq.org/sober.flatpakref"
]
