[managers.system]
items = [
  # Window Manager
	"hyprland", # Main Window Manager

	# Window Manager Essentials
	"hypridle", # Idle daemon, useful for auto-locking the screen & etc
	"hyprlock", # Screen lock for Hyprland
	"hyprpicker", # Utility to pick colors from the Hyprland screen
  "hyprshot", # Screenshot tool for Hyprland #TODO: Investigate flameshot
  # "gui-apps/hyprsysteminfo", # GUI app to display system information #TODO: Wrong package name, is it avail on gentoo?
  "rofi-wayland", # App launcher
  "swww", # Wallpaper manager
  "waybar", # Status bar
  "hyprcursor", # New cursor theme
	"xdg-desktop-portal-hyprland", # Handles a lot of Hyprland additions, e.g. file-picking & screen-sharing
  #"flameshot", # Investigate this vs hyprshot
  #"kde-misc/krusader", # File Explorer (might switch, check out pcmanfm)
  "hyprpolkitagent", # Polkit authentication daemon
	"kitty", # Terminal Emulator
]
