[managers.system]
items = [
  "app-emulation/libvirt",
  "app-emulation/qemu", # Allows for QEMU emulation
  "app-emulation/virt-manager", # GUI manager for machine emulation
]

[managers.openrc_default]
items = [
  "libvirtd",
]
