[managers.init]
items = [
  "app-admin/sudo", # requires additional configuration
  "app-eselect/eselect-repository", # requires additional configuration
  "dev-lang/rust-bin",
  "sys-apps/flatpak", # requires additional configuration
]

[managers.system]
items = [
# System Utilities
  "app-admin/syslog-ng", # Logging
  "app-admin/logrotate", # Weak dependency for app-admin/syslog-ng
  "app-laptop/laptop-mode-tools", # Tools for laptop users
  "net-fs/cifs-utils", # Support for SMB shares
  "net-misc/chrony", # NTP daemon
  "net-misc/dhcpcd", # Backup DHCP daemon
  "net-misc/networkmanager", # Requires additional use flags
  "net-wireless/iwd", # Backup wireless daemon
  "net-wireless/wpa_supplicant", # Backup wireless daemon
  "net-vpn/networkmanager-openconnect", # Support for VPN connections (OpenConnect)
  "net-vpn/networkmanager-openvpn", # Support for VPN connections (OpenVPN)
  "sys-apps/dbus", # Inter-process Communication (IPC) system
  "sys-apps/pciutils", # Various utilities regarding PCI devices
  "sys-auth/elogind", # Init login system
  "sys-fs/btrfs-progs", # Support for BTRFS
  "sys-fs/dosfstools", # Support for DOS (BIOS stuff)
  "sys-fs/e2fsprogs", # Suport for EXT
  "sys-fs/f2fs-tools", # Support for F2FS (Nice for USBs)
  "sys-fs/fuse:0", # AppImage dependency #TODO: Investigate me
  "sys-fs/xfsprogs", # Support for XFS
  "sys-fs/zfs", # Support for ZFS
  "sys-kernel/modprobed-db", # Disables modules not-in-use by kernel, #TODO: requires additional configs
  "sys-process/cronie", # Crontab daemon

# Core Utilities
  "app-admin/stow", # Essential for managing dotfiles, requires additional configs (pulling git repo & other shit)
  "app-arch/bzip2", # Support for bz2 archives
  "app-arch/gzip", # Support for gz archives
  "app-arch/p7zip", # Support for 7z archives
  "app-arch/tar", # Support for tar archives
  "app-arch/unzip", # Support for zip archives
  "app-arch/xz-utils", # Support for xz archives
  "app-arch/zip", # Support for zip archives
  "app-arch/zstd", # Support for zstd arcivces
  "app-misc/brightnessctl", # Brightness settings for laptops (CLI)
  "app-misc/fastfetch", # Displays information about the current system
  "app-misc/nerdfetch", # Displays less information than fastfetch, but in cool fonts (requires nerdfonts). Requires GURU repository
  "app-misc/tmux", # Terminal multiplexer (better than screen)
  "app-portage/gentoolkit", # Useful utilities with Gentoo & Portage
  "app-shells/bash-completion", # Allows for auto-completion for BASH
  "app-text/tree", # Displays files in a tree
  "app-text/wgetpaste", # Allows for pasting of logs for assists with errors
  "dev-util/pkgdev", # Portage utilities
  "dev-vcs/git", # Version manager, very essential #TODO: Redo description, version manager is not the right word
  "sys-apps/hwdata", # Provides useful hardware data
  "sys-apps/pciutils", # Provides useful PCI data
  "sys-process/btop",
  "sys-process/htop",

# Extended Utilities
  "app-shells/fzf", # Terminal fuzzy finder, requires additional configurations
  "app-shells/zoxide", # Better version of cd, requires additional configurations
  "app-shells/zsh", # Improvement on BASH, requires a .zshrc file
  "app-shells/zsh-completions", # Auto-completions for ZSH
  "dev-util/git-delta", # Allows for better Git differences
  "media-video/ffmpeg", # Utility for manipulating audio/video
  "net-analyzer/nmap", # Useful for scanning networks
  "net-misc/yt-dlp", # YouTube video downloader
  "sys-apps/bat", # Better version of cat. Cat is still useful, so do not alias. Requiers additional configurations
  "sys-apps/eza", # Better version of ls. Requires additional configurations
  "sys-apps/fd", # Better version of find #TODO: Redo descrption
  "sys-libs/gpm", # General Purpose Mouse server, allows mouse in tty mode
  "sys-power/tlp", # Laptop power utility

# Password Manager
  "app-admin/pass", # Password manager
  "app-admin/pass-otp", # Allows for OTP with password manager
  "app-crypt/gpgme", # GPG key functionality
  "app-crypt/pinentry", 
  "app-eselect/eselect-pinentry",
  "net-misc/keychain",
  "media-gfx/zbar", # Converts qrcodes to text, app-admin/pass-otp utility

# Text Editors
  "app-editors/nano", # Backup to NVIM
  "app-editors/neovim", # Main text editor/IDE, configurations on github
  "app-editors/vim", # Backup to NVIM
  "media-fonts/nerdfonts", # Adds new fonts (specified in use flags) and symbols
  "net-libs/nodejs", # Dependency for NVIM configurations

# Fonts
  "media-fonts/noto", # Noto fonts
  "media-fonts/noto-cjk", # CJK fonts
  "media-fonts/noto-emoji", # Add support for emojis

# Terminal Web Browser
  "www-client/links", # Web browser within the terminal, useful for crawling thru download pages, also as a backup
  ]

  [managers.cargo]
  items = [
# Core Utilities
    "rebos",

# Extended Utilities
    "cargo-expand", # Wrapper around rustc -Zunpretty=expanded. Shows the result of macro expansion and #[derive] expansion
    "cargo-info", # Extends cargo to query crates.io registry for crates details
    "cargo-update", # A cargo subcommand for checking and applying updates to installed executables
    "cermic", # Print .png images in your terminal as ascii art
    "shabi", # (S)imple (H)ex (A)nd (B)inary (I)nspector - CLI Tool
    "tlrc", # Tldr but rust
    "ttyper", # Terminal-based typing test
    "tui48", # An elegant and faithful 2048 clone in the terminal
    "tuido", # Terminal-basd to-do list
    "yazi-fm", # Terminal file manager
  ]

  [managers.openrc_default]
  items = [
    "chronyd",
    "cronie",
    "NetworkManager",
    "pcscd",
    "sshd",
  ]

  [managers.openrc_boot]
  items = [
    "elogind",
    "syslog-ng",
  ]
