[managers.init]
items = [
  "dnf-plugins-core", # Required for docker
  "flatpak", # Flatpak
  "rust", # RUST language (enables crate support)
]

[managers.system]
items = [
# System Utilities
  "cifs-utils", # Enable SMB shares
  "pinentry-curses", # Useful utility, required for GPG stuff
  "pinentry-tty", # Useful utility, required for GPG stuff

# Core Utilities
  "btop", # Shows process information
  "cronie", # Crontab daemon
  "fastfetch", # Displays information about the current system
  "git", # Version manager, very essential #TODO: Redo description, version manager is not the right word
  "htop", # Shows process information
  "hwdata", # Provides useful hardware data
  "stow", # Essential for managing dotfiles, requires additional configs (pulling git repo & other shit)
  "tmux", # Terminal multiplexer (better than screen)
  "tree", # Displays files in a tree
  "pciutils", # Provides useful PCI data

# Extended Utilities
  "bat", # Better version of cat. Cat is still useful, so do not alias. Requiers additional configurations
  "eza", # Better version of ls. Requires additional configurations
  "fd", # Better version of find #TODO: Redo descrption
  "ffmpeg-free", # Utility for manipulating audio/video
  "fzf", # Terminal fuzzy finder, requires additional configurations
  "git-delta", # Allows for better Git differences
  "nmap", # Useful for scanning networks
  "yt-dlp", # YouTube video downloader
  "zoxide", # Better version of cd, requires additional configurations
  "zsh", # Improvement on BASH, requires a .zshrc file

# Password Manager
  "pass", # Password manager
  "pass-otp", # Allows for OTP with password manager
  "keychain",
  "zbar", # Converts qrcodes to text, app-admin/pass-otp utility

# Text Editors
  "nano", # Backup to NVIM
  "neovim", # Main text editor/IDE, configurations on github
  "vim", # Backup to NVIM

# Fonts
  "google-noto-fonts-all", # Noto fonts

# Terminal Web Browser
  "links", # Web browser within the terminal, useful for crawling thru download pages, also as a backup
  ]

  [managers.cargo]
  items = [
# Core Utilities
    "rebos",

# Extended Utilities
    "tlrc", # tldr but rust
    "yazi-fm",
  ]

  [managers.systemctl_default]
  items = [
    "chronyd",
    "cronie",
    "NetworkManager",
    "sshd",
  ]
