[managers.system]
items = [
  "ansible", # Infrastructure as Code software
  "opentofu", # Terraform fork
  # "app-containers/docker", # Containerization software
  # "app-containers/docker-compose", # Contaiers as Code service for Docker
  # "app-containers/docker-swarm", # Cluster Docker containers
  # "app-containers/podman", # Containerization software
  # "app-containers/podman-compose", # Run docker-compose using Podman
  # "app-containers/podman-tui", # Terminal user interface for Podman
  "@container-management", # Containerization software
]
